{
 "title": "Solaranlage Kostal",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Übersicht AC",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Netzbezug AC",
     "measurement": "BB-solar",
     "select": [
      [
       { "params": [ "devices:local_HomeGrid_P" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Erzeugung AC",
     "measurement": "BB-solar",
     "select": [
      [
       { "params": [ "devices:local:ac_InvOut_P" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Hausverbrauch AC",
     "measurement": "BB-solar",
     "query": "SELECT \"devices:local:powermeter_P\" +\"devices:local:ac_InvOut_P\" FROM \"BB-solar\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "devices:local:powermeter_P" ], "type": "field" }
      ],
      [
       { "params": [ "devices:local:ac_InvOut_P" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Abregelung",
     "measurement": "BB-solar",
     "query": "SELECT \"devices:local_LimitEvuAbs\" FROM \"BB-solar\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "devices:local_HomeGrid_P" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "PV Erzeugung DC",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "DC1+DC2",
     "measurement": "BB-solar",
     "query": "SELECT \"devices:local:pv1_P\" +\"devices:local:pv2_P\" FROM \"BB-solar\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "devices:local:pv1_P" ], "type": "field" },
       { "params": [ "+" ], "type": "math" }
      ],
      [
       { "params": [ "devices:local:pv2_P" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "DC1",
     "measurement": "BB-solar",
     "select": [
      [
       { "params": [ "devices:local:pv1_P" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "DC2",
     "measurement": "BB-solar",
     "select": [
      [
       { "params": [ "devices:local:pv2_P" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eigenverbrauch",
   "type": "graph",
   "description": "siehe: https://solaranzeige.de/phpBB3/viewtopic.php?t=698\nAchtung: 120 ist die Sample-Rate!",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BB-solar",
     "query": "SELECT (sum(\"devices:local:ac_P\")-(sum(\"devices:local_HomeOwn_P\")+ sum(\"devices:local_HomeGrid_P\")))  /1000 /120  FROM \"BB-solar\" WHERE $timeFilter  and (\"devices:local:ac_P\" - (\"devices:local_HomeOwn_P\"+ \"devices:local_HomeGrid_P\"))>0 GROUP BY time(1d)  fill(null)",
     "select": [
      [
       { "params": [ "devices:local:ac_P" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Eigenverbrauch",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BB-solar",
     "query": "SELECT (sum(\"devices:local_HomePv_P\"))  /1000 /120  FROM \"BB-solar\" WHERE $timeFilter  and (\"devices:local_HomePv_P\" )>0 GROUP BY time(1d)  fill(null)",
     "select": [
      [
       { "params": [ "devices:local:ac_P" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "graph",
   "description": "siehe: https://solaranzeige.de/phpBB3/viewtopic.php?t=698\nAchtung: 120 ist die Sample-Rate!",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Hausverbrauch",
     "measurement": "BB-solar",
     "query": "SELECT (sum(\"devices:local_HomeOwn_P\") + sum(\"devices:local_HomeGrid_P\")) /1000 /120  FROM \"BB-solar\" WHERE  \"devices:local_HomeOwn_P\" +  \"devices:local_HomeGrid_P\" > 0 GROUP BY time(1d)  fill(null)",
     "select": [
      [
       { "params": [ "devices:local:ac_P" ], "type": "field" }
      ],
      [
       { "params": [ "devices:local_HomeOwn_P" ], "type": "field" }
      ],
      [
       { "params": [ "devices:local_HomePv_P" ], "type": "field" }
      ],
      [
       { "params": [ "devices:local_HomeGrid_P" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Eigenverbrauch",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BB-solar",
     "query": "SELECT (sum(\"devices:local_HomePv_P\"))  /1000 /120  FROM \"BB-solar\" WHERE $timeFilter  and (\"devices:local_HomePv_P\" )>0 GROUP BY time(1d)  fill(null)",
     "select": [
      [
       { "params": [ "devices:local:ac_P" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}